/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zjut_alan_opencvdemo_c7_DisplayModeActivity */

#ifndef _Included_zjut_alan_opencvdemo_c7_DisplayModeActivity
#define _Included_zjut_alan_opencvdemo_c7_DisplayModeActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zjut_alan_opencvdemo_c7_DisplayModeActivity
 * Method:    faceDetection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_zjut_alan_opencvdemo_c7_DisplayModeActivity_faceDetection
  (JNIEnv *, jobject, jlong);

/*
 * Class:     zjut_alan_opencvdemo_c7_DisplayModeActivity
 * Method:    initLoad
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_zjut_alan_opencvdemo_c7_DisplayModeActivity_initLoad
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
